# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
    lane :build_simulator do
      gym(
        scheme: "GentleDesignShowcase",
        project: "GentleDesignShowcase.xcodeproj",
        configuration: "Debug",

        sdk: "iphonesimulator",
        destination: "generic/platform=iOS Simulator",
        skip_archive: true,        # key: build, don't archive
        clean: true,

        derived_data_path: "build/DerivedData",
        buildlog_path: "build/logs"
      )
    end
end
