# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run unit tests"
  lane :unit_tests do
    sh("rm -rf ../fastlane/test_output")

    scan(
      workspace: "GentleDesignShowcase.xcworkspace",
      scheme: "GentleDesignShowcase",
      device: "iPhone 17",
      clean: true,

      code_coverage: true,

      # make paths deterministic
      derived_data_path: "fastlane/derived_data",
      result_bundle: true,
      result_bundle_path: "fastlane/test_output/GentleDesignShowcase.xcresult",

      output_directory: "fastlane/test_output"
    )
  end
end

